### PR TITLE
Added transformer to remove non-printing values.

### LINKED ISSUE #29: Remove `null` values from `html` output
Currently, the `html` tag produces invalid markup when a `null` value is encountered:

```js
import {html} from 'common-tags'

const todos = [{
  task: 'some task',
  done: false
}, {
  task: 'other task',
  done: true
}]

html`
  <h1>Incomplete tasks:</h1>
  <ul>
    ${todos.map((t) => t.done ? null : `<li>${t.task}</li>`)}
  </ul>
`
```

Produces:

```html
<h1>Incomplete tasks</h1>
<ul>
  <li>some task</li>
  null
</ul>
```

### PR DESCRIPTION
**Pull request by shannonmoeller**
Resolves #29.

### CODE REVIEW

**Comment by shannonmoeller** [comment]
Looks like the travis tests actually passed, but the Node 4 process terminated early when running an unrelated and untouched test.

**Comment by declandewet** [comment]
Thanks for getting around to this - I've had a lot on my plate recently. Yeah, sometimes the tests get a little messed up, but rarely on Travis - mostly appveyor because it's so slow. Just want to trigger a rebuild to be exactly sure before merge... :)

**Comment by declandewet** [comment]
Seems that this error is due to an uncaught exception. Everything seems fine on Node 5 and 6, so I'm going to merge this in for the time being but will have to investigate this error a little more before publishing the next release, as I'm not convinced this is travis-specific

**Comment by shannonmoeller** [comment]
Ok. I'll try and take a look tonight, too.

**Pull request merged**
