### PR TITLE
Don't insert a conjunction if the substition array contains only one item

### LINKED ISSUE #116: Comma lists methods don't work when an array has one item
Given the following code
```
import { oneLineCommaListsAnd } from 'common-tags'
console.log(oneLineCommaListsAnd`${['foo']}`)
```
I would expect the output to be `foo`, but the ourput is acutally `andfoo`.

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #116

### CODE REVIEW

**Comment by fatfisz** [comment]
Hi, good catch and thanks for the fix!

I'd be very much interested in merging this, but there is a thing that needs to be fixed beforehand: after upgrading `ava` some behavior around the CWD has changed and as a result all `readFromFixture` calls need to receive `__dirname` as the first parameter. Could you fix that up?

Also, could you also add yourself to the list of contributors in `package.json`?

**Comment by LucianBuzzo** [comment]
@fatfisz Sure thing, I'll update this now

**Comment by LucianBuzzo** [comment]
@fatfisz I've updated the PR with the changes you mentioned and rebased against master, we should be good to go :+1:

**Comment by fatfisz** [comment]
Thanks for the contribution! I'm planning on releasing this sometime during the next 24h - I'll give you a heads up.

**Comment by fatfisz** [comment]
This fix was released in 1.5.0!

**Pull request merged**
