### PR TITLE
migrate to jest from ava

### PR DESCRIPTION
**Pull request by declandewet**

### CODE REVIEW

**Comment by declandewet** [comment]
The build is failing on Node.js 5 because Jest test files have to be transpiled - I for some reason cannot get it to actually detect that we're using Babel. I will take a look at this later as it seems I have run out of time for now.

**Comment by declandewet** [comment]
Turned out the issue was just with JSDom. Had to switch to Node.js test runner. I'm not too happy about the amount of config this took, but my prediction that CI build speeds would improve was right on the money - CI is now happening 4-5 times faster than it was before this PR. The next sprint will likely make CI faster as its simply reconfiguring CI especially for that purpose. As for configs, the TypeScript sprint should improve that marginally.

I took the liberty of adjusting some of the linting config in this release, as I was still being shouted at by my IDE for a few things. One drawback is that we've had to drop the `use strict` directive in config files, but since they're just config files, I'm happy to make that sacrifice.

**Comment by fatfisz** [comment]
About `--ignore-pattern '!.*rc.js'` - I had the same problem today too and it turns out that in Windows cmd arguments like `.*rc.js` are not expanded, but in bash, etc. they are. I solved it by wrapping `.*rc.js`, like so: `'.*rc.js'`.

**Comment by declandewet** [comment]
I’m fine with that, when it comes to Windows my stance is to not bother fighting with build tools built for bash. Anyone with issues on windows can simply run docker, vagrant, git bash, conemu or whatever to get ahead of bash shortcomings on windows.

**Pull request merged**
