### PR TITLE
Fix InlineArrayTransformer adding extra newlines when maintaining indentation [WIP]

### PR DESCRIPTION
**Pull request by ibrahima**
The latter test tests behavior that I think should be correct, but it
fails because it is not the current behavior.

### CODE REVIEW

**Comment by fatfisz** [comment]
Hi, what a good catch!

Answering your question from #113: I think using a negation in this case is just fine because it should be future-proof.

**Comment by fatfisz** [comment]
@ibrahima I don't have permissions to re-run the build, but OTOH you could add a commit that adds you to contributors in `package.json`. Could you please do that and then we could go ahead with the merge if everything's green?

**Comment by ibrahima** [comment]
I just pushed a merge commit; I feel weird adding myself to contributors in package.json since it's a small patch, and not all the existing contributors on Github are in there. But anyway, CI should run again now.

**Comment by fatfisz** [comment]
If that's how you feel, then ok. If you change your mind though, don't hesitate to get back to us - you actually found the root cause and spent some time on fixing the problem, which is much more than most people do. If this is not worthy a mention in `package.json`, then I don't know what is 😉

**Comment by fatfisz** [comment]
Released in v1.5.0!

**Comment by ibrahima** [comment]
Thanks!

**Pull request merged**
